DPS_METADATA = {
    "1":  {"name": "SoC Batterie 1",      "type": "int",  "writable": False},
    "2":  {"name": "Kapazität Wh",        "type": "int",  "writable": False},
    "10": {"name": "Temperatur",          "type": "int",  "writable": False},
    "25": {"name": "AC verfügbar",        "type": "bool", "writable": True},
    "101": {"name": "Systembereit",       "type": "bool", "writable": False},
    "102": {"name": "Modus",              "type": "str",  "writable": True},
    "103": {"name": "DC Input",           "type": "int",  "writable": False},
    "104": {"name": "DC Input 2",         "type": "int",  "writable": False},
    "105": {"name": "DC Output",          "type": "int",  "writable": False},
    "106": {"name": "AC Output",          "type": "int",  "writable": False},
    "108": {"name": "Output-Leistung",    "type": "int",  "writable": False},
    "109": {"name": "AC Out AN",          "type": "bool", "writable": True},
    "110": {"name": "AC Frequenz",        "type": "int",  "writable": False},
    "111": {"name": "USB 5V AN",          "type": "bool", "writable": True},
    "112": {"name": "DC 12V AN",          "type": "bool", "writable": True},
    "113": {"name": "Ladegrenze 1",       "type": "int",  "writable": False},
    "114": {"name": "Ladegrenze 2",       "type": "int",  "writable": False},
    "115": {"name": "?",                  "type": "int",  "writable": False},
    "116": {"name": "?",                  "type": "int",  "writable": False},
    "117": {"name": "?",                  "type": "int",  "writable": False},
    "118": {"name": "?",                  "type": "int",  "writable": False},
    "120": {"name": "AC Einschaltzeit",   "type": "str",  "writable": True},
    "121": {"name": "AC Dauer",           "type": "str",  "writable": True},
    "122": {"name": "AC Ausschaltzeit",   "type": "str",  "writable": True},
    "123": {"name": "AC Zielwert %",      "type": "int",  "writable": True},
    "124": {"name": "Feature 1",          "type": "bool", "writable": True},
    "125": {"name": "Feature 2",          "type": "bool", "writable": True},
    "126": {"name": "Feature 3",          "type": "bool", "writable": True},
    "127": {"name": "Systemmodus",        "type": "str",  "writable": False},
    "128": {"name": "Feature 4",          "type": "bool", "writable": True},
    "130": {"name": "HW Version",         "type": "str",  "writable": False},
    "132": {"name": "Firmware",           "type": "str",  "writable": False},
    "133": {"name": "BMS Version",        "type": "str",  "writable": False},
    "134": {"name": "?",                  "type": "int",  "writable": False},
    "135": {"name": "?",                  "type": "int",  "writable": False},
    "136": {"name": "?",                  "type": "int",  "writable": False},
    "137": {"name": "BMS Status",         "type": "int",  "writable": False},
    "138": {"name": "SoC Zusatzbatt.",    "type": "int",  "writable": False},
    "139": {"name": "?",                  "type": "int",  "writable": False},
    "140": {"name": "Seriennummer",       "type": "str",  "writable": False},
    "143": {"name": "?",                  "type": "int",  "writable": False},
    "145": {"name": "Netzspannung",       "type": "int",  "writable": True}
}
